In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ir_rpp.preprocessing import load_dfs
from ir_rpp.statistical_tests import run_ttests, run_tukeys_hsd_test


%load_ext autoreload
%autoreload 2

In [12]:
summary, df_preference, df_metric = load_dfs("beerAdvocate", binary_relevance=3.5)

Reading run files: 100%|██████████| 21/21 [01:15<00:00,  3.59s/it]

Iterating over qids:   0%|          | 0/17564 [00:00<?, ?it/s]

In [14]:
df_ttest, df_summary = run_ttests(df_preference)
df_summary

metric         rpp  invrpp  dcgrpp     ap   ndcg     rr
significant  95.24   95.24   95.24  93.33  97.14  93.33

In [15]:
df_tukey, summary = run_tukeys_hsd_test(
    df_preference,
    metrics=["rpp", "invrpp", "dcgrpp", "ap", "ndcg", "rr"],
    n_permutations=2000
)

Building Data Matrix: 100%|██████████| 3688440/3688440 [01:16<00:00, 48322.41it/s]
Permutation Trials for rpp: 100%|██████████| 2000/2000 [01:37<00:00, 20.46it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 86889.99it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:15<00:00, 48582.91it/s]
Permutation Trials for invrpp: 100%|██████████| 2000/2000 [01:37<00:00, 20.53it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 82487.72it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:16<00:00, 48514.59it/s]
Permutation Trials for dcgrpp: 100%|██████████| 2000/2000 [01:37<00:00, 20.48it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 101009.61it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:15<00:00, 48945.34it/s]
Permutation Trials for ap: 100%|██████████| 2000/2000 [01:37<00:00, 20.50it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 80094.92it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:15<00:00, 48968.11it/s]
Permutation Trials for ndcg: 100%|██████████| 2000/2000 [01:36<00:00, 20.68it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 83504.35it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:17<00:00, 47890.95it/s]
Permutation Trials for rr: 100%|██████████| 2000/2000 [01:38<00:00, 20.34it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 76498.51it/s]

In [16]:
summary

metric         rpp  invrpp  dcgrpp     ap   ndcg    rr
significant  93.81   94.29   93.33  92.38  94.29  91.9

### DL 2020 Passage

In [37]:
summary, df_preference, df_metric = load_dfs("dl20-passage", binary_relevance=2)

Reading run files: 100%|██████████| 59/59 [00:10<00:00,  5.51it/s]

Iterating over qids:   0%|          | 0/54 [00:00<?, ?it/s]

In [39]:
df_tukey, summary = run_tukeys_hsd_test(
    df_preference,
    metrics=["rpp", "invrpp", "dcgrpp", "ap", "ndcg", "rr"],
    n_permutations=2000
)

Building Data Matrix: 100%|██████████| 92394/92394 [00:01<00:00, 48461.84it/s]
Permutation Trials for rpp: 100%|██████████| 2000/2000 [00:00<00:00, 4902.61it/s]
Comparing Pairs: 100%|██████████| 1711/1711 [00:00<00:00, 187752.25it/s]
Building Data Matrix: 100%|██████████| 92394/92394 [00:01<00:00, 47147.42it/s]
Permutation Trials for invrpp: 100%|██████████| 2000/2000 [00:00<00:00, 4878.48it/s]
Comparing Pairs: 100%|██████████| 1711/1711 [00:00<00:00, 192032.70it/s]
Building Data Matrix: 100%|██████████| 92394/92394 [00:01<00:00, 48208.33it/s]
Permutation Trials for dcgrpp: 100%|██████████| 2000/2000 [00:00<00:00, 4908.48it/s]
Comparing Pairs: 100%|██████████| 1711/1711 [00:00<00:00, 198744.20it/s]
Building Data Matrix: 100%|██████████| 92394/92394 [00:01<00:00, 48168.79it/s]
Permutation Trials for ap: 100%|██████████| 2000/2000 [00:00<00:00, 4906.04it/s]
Comparing Pairs: 100%|██████████| 1711/1711 [00:00<00:00, 189452.33it/s]
Building Data Matrix: 100%|██████████| 92394/92394 [00:01<00:00, 48034.69it/s]
Permutation Trials for ndcg: 100%|██████████| 2000/2000 [00:00<00:00, 4830.74it/s]
Comparing Pairs: 100%|██████████| 1711/1711 [00:00<00:00, 182171.25it/s]
Building Data Matrix: 100%|██████████| 92394/92394 [00:01<00:00, 48236.31it/s]
Permutation Trials for rr: 100%|██████████| 2000/2000 [00:00<00:00, 4908.36it/s]
Comparing Pairs: 100%|██████████| 1711/1711 [00:00<00:00, 190069.50it/s]

In [40]:
summary

metric         rpp  invrpp  dcgrpp    ap  ndcg    rr
significant  12.22   13.21   13.33  7.83  7.19  0.06

## Load Data

In [ ]:
# Load data
rows = []
with open("../../data/beerAdvocate/all_results.jsonl", "r") as f:
    for line in f:
        rows.append(json.loads(line))

df = pd.DataFrame(rows)

metrics = ["rpp", "invrpp", "dcgrpp", "ap", "rbp", "rr", "ndcg", "rp"]

# Filter for preference rows only
# each row contains System A vs System B deltas for every query
df_pref = df[df['type'] == 'preference'].copy()

# Group by the pairs
pairs = df_pref.groupby(['runi', 'runj'])

results_table = []

for (run_i, run_j), group in pairs:
    pair_results = {"pair": f"{run_i}:{run_j}"}

    for m in metrics:
        # Distribution of differences (eg. SystemA_NDCG - SystemB_NDCG)
        scores = group[m].dropna()

        t_stat, p_val = ttest_1samp(scores, 0)
        
        pair_results[f"{m}_p"] = p_val
        pair_results[f"{m}_mean"] = scores.mean()
        
    results_table.append(pair_results)

df_stats = pd.DataFrame(results_table)

## t-test + Bonferroni

The table is based on pairwise differences.

In [17]:
df_hard = df_stats[abs(df_stats['ndcg_mean']) < 0.01]

alpha = 0.05
num_pairs = len(df_hard)
bonferroni_threshold = alpha / num_pairs # keep the overall error rate at 0.05 across all pairs
extreme_threshold = 1e-10

print(f"Percentage of significant differences (t-test, Bonferroni @ {bonferroni_threshold:.6e}):")
for m in metrics:
    sig_count = (df_hard[f"{m}_p"] < bonferroni_threshold).sum()
    percentage = (sig_count / num_pairs) * 100
    print(f"{m:15}: {percentage:.2f}%")

Percentage of significant differences (t-test, Bonferroni @ 2.000000e-03):
rpp            : 76.00%
invrpp         : 84.00%
dcgrpp         : 76.00%
ap             : 68.00%
rbp            : 60.00%
rr             : 56.00%
ndcg           : 84.00%
rp             : 76.00%

## Tukey’s HSD

In [22]:
import json 

# Retrieve the absolute metric scores
metric_rows = []
with open("../../data/beerAdvocate/all_results.jsonl", "r") as f:
    for line in f:
        data = json.loads(line)
        if data.get("type") == "metric":
            metric_rows.append(data)

df_absolute = pd.DataFrame(metric_rows)
df_absolute.dtypes

KeyboardInterrupt:

In [ ]:

print("=== Table 3: Tukey's HSD Sensitivity ===")
for m in ["ap", "ndcg", "rr", "rp"]:
    if m in df_absolute.columns:
        df_absolute[m] = pd.to_numeric(df_absolute[m], errors='coerce')
            
        res = pairwise_tukeyhsd(endog=df_absolute[m], groups=df_absolute['run'], alpha=0.05)
            
        sig_count = res.reject.sum()
        total_pairs = len(res.reject)
        percentage = (sig_count / total_pairs) * 100
        print(f"{m:10}: {percentage:.2f}% of pairs are significantly different")

# For RPP and variants (using the preference p-values in df_stats) use p < 0.05 without Bonferroni to match Tukey's sensitivity level
num_pairs = len(df_stats)
for m in ["rpp", "invrpp", "dcgrpp"]:
    sig_count = (df_stats[f"{m}_p"] < 0.05).sum()
    percentage = (sig_count / num_pairs) * 100
    print(f"{m:10}: {percentage:.2f}% of pairs are significantly different")