# Student test and Adapted HSD Test for Single Topic

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ir_rpp.preprocessing import load_dfs, dataset_summary, load_labels_and_runs
from ir_rpp.statistical_tests import run_ttests, run_tukeys_hsd_test


%load_ext autoreload
%autoreload 2

### Load data

In [2]:
summary, df_preference, df_metric = load_dfs("beerAdvocate", binary_relevance=3.5)

Reading run files: 100%|██████████| 21/21 [01:10<00:00,  3.35s/it]

Iterating over qids:   0%|          | 0/17564 [00:00<?, ?it/s]

### Statistics check

- requests
- runs
- rel/request
- subtopics/request

In [ ]:
qrels_2009, runs_2009 = load_labels_and_runs("web", 2009, binary_relevance=3.5)
print(dataset_summary(qrels_2009, runs_2009))

### Student’s 𝑡 -test with Bonferroni correction

In [14]:
df_ttest, df_summary = run_ttests(df_preference)
df_summary

metric         rpp  invrpp  dcgrpp     ap   ndcg     rr
significant  95.24   95.24   95.24  93.33  97.14  93.33

### Tukey’s HSD test

In [ ]:
df_tukey, summary = run_tukeys_hsd_test(
    df_preference,
    metrics=["rpp", "invrpp", "dcgrpp", "ap", "ndcg", "rr"],
    n_permutations=2000
)
summary

Building Data Matrix: 100%|██████████| 3688440/3688440 [01:16<00:00, 48322.41it/s]
Permutation Trials for rpp: 100%|██████████| 2000/2000 [01:37<00:00, 20.46it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 86889.99it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:15<00:00, 48582.91it/s]
Permutation Trials for invrpp: 100%|██████████| 2000/2000 [01:37<00:00, 20.53it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 82487.72it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:16<00:00, 48514.59it/s]
Permutation Trials for dcgrpp: 100%|██████████| 2000/2000 [01:37<00:00, 20.48it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 101009.61it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:15<00:00, 48945.34it/s]
Permutation Trials for ap: 100%|██████████| 2000/2000 [01:37<00:00, 20.50it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 80094.92it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:15<00:00, 48968.11it/s]
Permutation Trials for ndcg: 100%|██████████| 2000/2000 [01:36<00:00, 20.68it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 83504.35it/s]
Building Data Matrix: 100%|██████████| 3688440/3688440 [01:17<00:00, 47890.95it/s]
Permutation Trials for rr: 100%|██████████| 2000/2000 [01:38<00:00, 20.34it/s]
Comparing Pairs: 100%|██████████| 210/210 [00:00<00:00, 76498.51it/s]

In [16]:
summary

metric         rpp  invrpp  dcgrpp     ap   ndcg    rr
significant  93.81   94.29   93.33  92.38  94.29  91.9