# Student test and Adapted HSD Test for Web Subtopic

The paper specifies the comparaison of four metrics:

- MAP-IA: No rank cutoff.

- ERR-IA@20: Rank cutoff of 20.

- ST-Recall(strec)@20: Rank cutoff of 20.

- ST-RPP: rpp metric, applied per subtopic and averaged.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ir_rpp.preprocessing import load_dfs, dataset_summary, load_labels_and_runs
from ir_rpp.statistical_tests import run_ttests, run_tukeys_hsd_test
from ir_rpp.pref_eval.measures.subtopic_metrics import *
from ir_rpp.utils import filter_valid_queries


%load_ext autoreload
%autoreload 2

### Load data

In [2]:
summary_2009, df_pref_2009, df_metric_2009 = load_dfs(
    dataset="web",
    year=2009,
    metrics=["st-rpp", "st-dcgrpp", "st-invrpp", "strec", "err-ia", "map-ia"],
    binary_relevance=1
)

Reading run files: 100%|██████████| 48/48 [00:03<00:00, 12.23it/s]

Iterating over qids:   0%|          | 0/50 [00:00<?, ?it/s]

### Statistics check

- requests
- runs
- rel/request
- subtopics/request

In [10]:
qrels_2009, runs_2009 = load_labels_and_runs("web", 2009, binary_relevance=1)
print(dataset_summary(qrels_2009, runs_2009))

Reading run files: 100%|██████████| 48/48 [00:04<00:00,  9.87it/s]

requests              50.00
runs                  48.00
rel/request          129.98
subtopics/request      4.98
dtype: float64

In [4]:
# Only for Web 2013 and Web 2014 t-test 

#df_metric_2013, df_pref_2013 = filter_valid_queries(df_metric_2013, df_pref_2013)

### Student’s 𝑡 -test with Bonferroni correction

In [5]:
df_ttest, df_summary = run_ttests(df_pref_2009, metrics=["st-rpp", "strec", "err-ia", "map-ia"])
df_summary

metric          st-rpp      strec     err-ia    map-ia
significant  33.244681  28.280142  24.113475  14.98227

### Tukey’s HSD test

In [6]:
df_tukey, summary = run_tukeys_hsd_test(
    df_pref_2009,
    metrics=["st-rpp", "strec", "err-ia", "map-ia"],
    n_permutations=2000
)
summary

Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 46757.29it/s]
Permutation Trials for st-rpp: 100%|██████████| 2000/2000 [00:00<00:00, 5442.29it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 172601.32it/s]
Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 48594.76it/s]
Permutation Trials for strec: 100%|██████████| 2000/2000 [00:00<00:00, 5446.62it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 181347.50it/s]
Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 48810.12it/s]
Permutation Trials for err-ia: 100%|██████████| 2000/2000 [00:00<00:00, 5443.76it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 178393.53it/s]
Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 48705.30it/s]
Permutation Trials for map-ia: 100%|██████████| 2000/2000 [00:00<00:00, 5418.08it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 177078.18it/s]

metric       st-rpp  strec  err-ia  map-ia
significant    30.5  28.55   25.27   17.29