# Student test and Adapted HSD Test for Web Subtopic

The paper specifies the comparaison of four metrics:

- MAP-IA: No rank cutoff.

- ERR-IA@20: Rank cutoff of 20.

- ST-Recall(strec)@20: Rank cutoff of 20.

- ST-RPP: rpp metric, applied per subtopic and averaged.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from ir_rpp.preprocessing import load_dfs, dataset_summary, load_labels_and_runs
from ir_rpp.statistical_tests import run_ttests, run_tukeys_hsd_test
from ir_rpp.pref_eval.measures.subtopic_metrics import *


%load_ext autoreload
%autoreload 2

In [2]:
summary_2009, df_pref_2009, df_metric_2009 = load_dfs(
    dataset="web",
    year=2009,
    metrics=["st-rpp", "st-dcgrpp", "st-invrpp", "strec", "err-ia", "map-ia"],
    binary_relevance=1
)

Reading run files: 100%|██████████| 48/48 [00:03<00:00, 12.12it/s]

Iterating over qids:   0%|          | 0/50 [00:00<?, ?it/s]

In [3]:
qrels_2009, runs_2009 = load_labels_and_runs("web", 2009, binary_relevance=1)
print(dataset_summary(qrels_2009, runs_2009))

Reading run files: 100%|██████████| 48/48 [00:04<00:00, 11.88it/s]

requests              50.00
runs                  48.00
rel/request          129.98
subtopics/request      4.98
dtype: float64

In [4]:
df_pref_2009.head()

,qid,runi,runj,sample,type,st-rpp,st-dcgrpp,st-invrpp,strec,err-ia,map-ia
0,1,udelFMWG,uogTrDYCcsB,1,preference,-0.609774,-0.706212,-0.834519,-0.666667,-0.924196,-0.296020
1,1,udelFMWG,twCSodpRBB,1,preference,0.477263,0.463473,0.254293,-0.666667,-0.888889,0.022738
2,1,udelFMWG,uwgym,1,preference,0.469033,0.449165,0.227507,-0.666667,-0.913889,0.030895
3,1,udelFMWG,RmitDiv,1,preference,0.498045,0.506163,0.349352,-0.666667,-0.833333,0.046672
4,1,udelFMWG,UamsDwebLFou,1,preference,-0.638735,-0.691361,-0.739719,-0.666667,-0.898611,-0.063572

In [5]:
df_metric_2009.head()

  qid          run  sample    type     strec    err-ia    map-ia
0   1     udelFMWG       1  metric  0.000000  0.000000  0.053355
1   1  uogTrDYCcsB       1  metric  0.666667  0.924196  0.349375
2   1   twCSodpRBB       1  metric  0.666667  0.888889  0.030616
3   1        uwgym       1  metric  0.666667  0.913889  0.022460
4   1      RmitDiv       1  metric  0.666667  0.833333  0.006682

In [6]:
df_ttest, df_summary = run_ttests(df_pref_2009, metrics=["st-rpp", "strec", "err-ia", "map-ia"])
df_summary

metric          st-rpp      strec     err-ia    map-ia
significant  33.244681  28.280142  24.113475  14.98227

In [7]:
df_tukey, summary = run_tukeys_hsd_test(
    df_pref_2009,
    metrics=["st-rpp", "strec", "err-ia", "map-ia"],
    n_permutations=2000
)
summary

Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 49358.56it/s]
Permutation Trials for st-rpp: 100%|██████████| 2000/2000 [00:00<00:00, 5548.54it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 175782.09it/s]
Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 49089.49it/s]
Permutation Trials for strec: 100%|██████████| 2000/2000 [00:00<00:00, 5570.00it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 177917.23it/s]
Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 49183.94it/s]
Permutation Trials for err-ia: 100%|██████████| 2000/2000 [00:00<00:00, 5473.58it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 176135.47it/s]
Building Data Matrix: 100%|██████████| 56400/56400 [00:01<00:00, 49115.18it/s]
Permutation Trials for map-ia: 100%|██████████| 2000/2000 [00:00<00:00, 5468.90it/s]
Comparing Pairs: 100%|██████████| 1128/1128 [00:00<00:00, 174023.43it/s]

metric       st-rpp  strec  err-ia  map-ia
significant   30.67  29.34   25.35   17.55